#!/usr/bin/env bash
unset TF_LOG OS_AUTH_URL OS_TENANT_NAME OS_USERNAME OS_REGION_NAME OS_DOMAIN_NAME OS_PROJECT_NAME OS_PROJECT_DOMAIN_NAME OS_PASSWORD
unset OS_USER_DOMAIN_NAME ARC_SERVICE_ENDPOINT LYRA_SERVICE_ENDPOINT ARC_BROKER_URL PKI_SERVICE_URL UPDATE_SERVICE_URL CLIENT_OS WORKSTATION_OS
export TF_LOG=INFO # other options are DEBUG TRACE INFO WARN ERROR
export CLIENT_OS=linux #Target OS type; Currently supported linux
export OS_IDENTITY_API_VERSION=3
export WORKSTATION_OS=darwin #linux for Linux; darwin for mac
export OS_AUTH_URL=https://identity-3.ap-au-1.cloud.sap:443/v3
export OS_TENANT_NAME="consulting_dev"
export OS_PROJECT_NAME=$OS_TENANT_NAME
# Your SAP C/I/D username eg., i123456 or d123456 with lowercase c/i/d.
export OS_USERNAME="c5240533"
if [ -z $OS_PASSWORD ]; then
   read -s -p "Enter Your Password:" OS_PASSWD
   export OS_PASSWORD=$OS_PASSWD
fi
export OS_REGION_NAME="ap-au-1" #Other region `ap-au-1`
export OS_DOMAIN_NAME="monsoon3" #Change your domain to suit
export OS_PROJECT_DOMAIN_NAME=$OS_DOMAIN_NAME
export OS_USER_DOMAIN_NAME=$OS_DOMAIN_NAME
#export ARC_SERVICE_ENDPOINT="https://arc.$OS_REGION_NAME.cloud.sap"
#export LYRA_SERVICE_ENDPOINT="https://lyra.$OS_REGION_NAME.cloud.sap"
#export ARC_BROKER_URL="tls://arc-broker.$OS_REGION_NAME.cloud.sap:8883"
#export PKI_SERVICE_URL="https://arc-pki.$OS_REGION_NAME.cloud.sap"
#export UPDATE_SERVICE_URL="https://stable.arc.$OS_REGION_NAME.cloud.sap"
alias tf="terraform"
